USE students;

insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060120023','系统工程原理',48,2.5,'大类基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060120033','风险分析与控制',32,2,'大类基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060130041','系统科学',32,2,'专业基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060130053','决策支持系统与知识工程',48,2.5,'专业基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060130061','系统数学',32,2,'专业基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060130073','运筹学（双语）',48,2.5,'专业基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060130083','多元统计分析',32,2,'专业基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060130093','信息系统工程',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140301','管理信息系统专题',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140313','数据库技术与应用',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140323','计算智能',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140331','数据挖掘方法与工具',48,2.5,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140341','复杂网络理论与方法',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140353','信息资源开发与管理',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140361','现代网络技术',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140373','信息与知识管理',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140381','信息安全管理与技术',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140393','系统开发理论与方法',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140403','电子商务',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140411','物流与供应链管理',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140421','移动计算与移动商务',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140431','软件工程',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140443','系统仿真',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140451','电子政务理论与方法',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140461','系统综合集成',48,2.5,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140471','应急管理理论与方法',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060140481','系统分析与设计',32,2,'专业选修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060220019','管理学原理',32,2,'大类基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2060330203','微观经济学',32,2,'专业基础课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2070110059','论文写作与学术规范',16,1,'公共必修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2070310013','中国特色社会主义理论与实践研究',36,2,'公共必修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2100010011','口语交流 I(基础口语表达)',16,1,'公共必修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2100010021','口语交流 II(学术交流)',16,1,'公共必修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2100010033','阅读与写作 I(基础读写技能)',32,2,'公共必修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2100010043','阅读与写作II(全球化研究，西方文学、哲学经典)',36,2,'公共必修课');
insert into `course`(`course_id`,`course_name`,`course_hour`,`course_credit`,`course_character`) values ('2120020023','优化方法',32,2,'大类基础课');
